const ADD_TO_CLIPBOARD = 'ADD_TO_CLIPBOARD';
const REMOVE_FROM_CLIPBOARD = 'REMOVE_FROM_CLIPBOARD';
const INPUT_CHANGE = 'INPUT_CHANGE';
const UPDATE_ENCODED_VALUE = 'UPDATE_ENCODED_VALUE';
const UPDATE_ENCODING_START_TYPE = 'UPDATE_ENCODING_START_TYPE';
const UPDATE_ENCODING_END_TYPE = 'UPDATE_ENCODING_END_TYPE';

export {
  ADD_TO_CLIPBOARD,
  REMOVE_FROM_CLIPBOARD,
  INPUT_CHANGE,
  UPDATE_ENCODED_VALUE,
  UPDATE_ENCODING_START_TYPE,
  UPDATE_ENCODING_END_TYPE,
};
