const ADD_TO_CLIPBOARD = 'ADD_TO_CLIPBOARD';
const REMOVE_FROM_CLIPBOARD = 'REMOVE_FROM_CLIPBOARD';
const INPUT_CHANGE = 'INPUT_CHANGE';
const UPDATE_DISPLAY_VALUE = 'UPDATE_DISPLAY_VALUE';

export {
  ADD_TO_CLIPBOARD,
  REMOVE_FROM_CLIPBOARD,
  INPUT_CHANGE,
  UPDATE_DISPLAY_VALUE,
};
